version: '3.8'

services:
    database:
        build:
            context: ./
            dockerfile: Dockerfile
            target: db_server
        container_name: database
        restart: unless-stopped
        tty: true
        command: [ "mysqld" ]
        entrypoint: [ "docker-entrypoint.sh" ]
        ports:
            - "0.0.0.0:3306:3306/tcp"
        networks:
            - bcycle-network
        volumes:
            - database-vol:/var/lib/mysql
            - ./database/bcycledb.sql:/docker-entrypoint-initdb.d/bcycledb.sql
        environment:
            DATADIR: /var/lib/mysql
            MYSQL_DATABASE: bcycle
            MYSQL_USER: bcycle
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
            MARIADB_ROOT_PASSWORD: password
        healthcheck:
            test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
            interval: 30s
            timeout: 5s
            retries: 3

    api:
        build:
            context: ./
            dockerfile: Dockerfile
            target: api_server
        container_name: apiserver
        restart: unless-stopped
        tty: true
        depends_on:
            database:
                condition: service_healthy
        ports:
            - "3000:3000/tcp"
        networks:
            - bcycle-network
        environment:
            DB_HOST: database
            DB_DATABASE: bcycle
            DB_USERNAME: bcycle
            DB_PASSWORD: password

    webserver:
        build:
            context: ./
            dockerfile: Dockerfile
            target: web_server
        container_name: webserver
        restart: unless-stopped
        tty: true
        depends_on:
            database:
                condition: service_healthy
            api:
                condition: service_started
        ports:
            - "80:80"
        networks:
            - bcycle-network
        volumes:
            - weblogs-vol:/var/log/nginx

networks:
    bcycle-network:

volumes:
    database-vol:
    weblogs-vol:


